receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logzio:
    account_token: ${LOGZIO_ACCOUNT_TOKEN}
    # region: "${LOGZIO_ACCOUNT_REGION}"  # Optionally replace with environment variable

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logzio]
